import argparse

parser = argparse.ArgumentParser(description="hyper-parameter for R2GenGPT")
# ========================= Runtime Configs ==========================
parser.add_argument('--config', type=str, default=None, help="optional JSON/YAML experiment config file")
parser.add_argument('--preflight_only', action='store_true', help="validate paths/config and exit before loading models")
parser.add_argument('--data_sample_check', type=int, default=0, help="number of samples per split to validate during preflight")
parser.add_argument('--require_branch_assets', default=False, type=lambda x: (str(x).lower() == 'true'), help="preflight branch/Chexbert asset paths")
parser.add_argument('--write_provenance', default=True, type=lambda x: (str(x).lower() == 'true'), help="write resolved config metadata into savedmodel_path")

# ========================= Dataset Configs ==========================
parser.add_argument('--test', action='store_true', help="only run test set")
parser.add_argument('--validate', action='store_true', help="only run validation set")
parser.add_argument('--dataset', type=str, default='mimic_cxr', help="iu-xray or mimic-cxr")
parser.add_argument('--annotation', type=str, default=r'./data/mimic_cxr/annotation.json', help="annotation file of the dataset")
parser.add_argument('--base_dir', type=str, default=r'./data/mimic_cxr/images', help="base dir to help find images")
parser.add_argument('--batch_size', default=6, type=int, help="use for training duration per worker")
parser.add_argument('--val_batch_size', default=16, type=int, help="use for validation duration per worker")
parser.add_argument('--test_batch_size', default=16, type=int, help="use for testing duration per worker")
parser.add_argument('--prefetch_factor', default=4, type=int, help="use for training duration per worker")
parser.add_argument('--num_workers', default=8, type=int, help="Cpu num for dataloaders")
parser.add_argument('--train_shuffle', default=True, type=lambda x: (str(x).lower() == 'true'), help="shuffle training dataset")
parser.add_argument('--persistent_workers', default=True, type=lambda x: (str(x).lower() == 'true'), help="keep dataloader workers alive between epochs")

# ========================= Model Settings ============================
parser.add_argument('--model_name', default='branchgpt', type=str, choices=['r2gengpt', 'branchgpt'], help="model class to use")
parser.add_argument('--vision_model', default='/public/home/ai_user_5/MRG/rad-dino', type=str, help="vision model to use")
parser.add_argument('--vision_model_type', default='auto', type=str, choices=['swin', 'auto'], help="vision model loader type")
parser.add_argument('--llama_model', default='/public/home/ai_user_5/MRG/Llama-2-7b-chat-hf', type=str, help="LLM model to use")
parser.add_argument('--freeze_vm', default=True, type=lambda x: (str(x).lower() == 'true'), help='freeze vision model')
parser.add_argument('--llm_use_lora', default=False, type=lambda x: (str(x).lower() == 'true'), help="whether use lora for LLM model")
parser.add_argument('--llm_r', default=16, type=int, help='The dimension used by the LoRA update matrices')
parser.add_argument('--llm_alpha', default=16, type=int, help='Scaling factor.')
parser.add_argument('--llm_lora_target_modules', default='q_proj,v_proj,k_proj,o_proj', type=str, help='comma-separated LoRA target modules for LLM')
parser.add_argument('--vis_lora_target_modules', default='query,value', type=str, help='comma-separated LoRA target modules for vision model')
parser.add_argument('--vis_use_lora', default=False, type=lambda x: (str(x).lower() == 'true'), help="whether use lora for vision model")
parser.add_argument('--vis_r', default=16, type=int, help='The dimension used by the LoRA update matrices')
parser.add_argument('--vis_alpha', default=16, type=int, help='Scaling factor.')
parser.add_argument('--lora_dropout', default=0.1, type=float, help='lora dropout')
parser.add_argument('--global_only', default=False, type=lambda x: (str(x).lower() == 'true'), help='use global embedding only')
parser.add_argument('--projector_type', default='qformer', type=str, choices=['linear', 'qformer'], help='visual-to-LLM projector')
parser.add_argument('--qformer_num_query_tokens', default=32, type=int, help='number of learned visual query tokens')
parser.add_argument('--qformer_num_layers', default=2, type=int, help='number of Q-Former cross-attention layers')
parser.add_argument('--qformer_num_heads', default=8, type=int, help='Q-Former attention heads')
parser.add_argument('--qformer_dropout', default=0.1, type=float, help='Q-Former dropout')
parser.add_argument('--low_resource', default=False, type=bool)
parser.add_argument('--end_sym', default='</s>', type=str)
parser.add_argument('--use_chat_template', default=False, type=lambda x: (str(x).lower() == 'true'), help='use tokenizer chat template for BranchGPT prompt')
parser.add_argument('--report_prompt', default='Generate a comprehensive and detailed diagnosis report for this chest xray image.', type=str, help='instruction prompt for report generation')
parser.add_argument('--use_label_prompt', default=False, type=lambda x: (str(x).lower() == 'true'), help='inject known KG labels into the report prompt')
parser.add_argument('--label_prompt_fraction', default=1.0, type=float, help='fraction of positive KG labels visible to the teacher prompt')
parser.add_argument('--label_prompt_max_items', default=32, type=int, help='maximum KG labels listed in the prompt')
parser.add_argument('--label_prompt_seed', default=42, type=int, help='deterministic seed for label-prompt subsampling')
parser.add_argument('--label_prompt_prefix', default='Known observations:', type=str, help='prefix text for label prompt injection')

# ======================== SavedModel Configs ===========================
parser.add_argument('--savedmodel_path', type=str, default='save/mimic/v1')
parser.add_argument('--ckpt_file', type=str, default=None, help='the checkpoint file to load')
parser.add_argument('--delta_file', type=str, default=None, help='the delta file to load')
parser.add_argument('--weights', type=list, default=[0.33, 0.33, 0.34])
parser.add_argument('--scorer_types', type=list, default=['Bleu_4', 'ROUGE_L'])

# ========================= Learning Configs ==========================
parser.add_argument('--learning_rate', default=1e-4, type=float, help='initial learning rate')
parser.add_argument('--gradient_clip_val', default=None, type=int, help='gradient clip value')
parser.add_argument('--weight_decay', default=0.01, type=float, help='AdamW weight decay')
parser.add_argument('--warmup_ratio', default=0.05, type=float, help='ratio of total steps used for linear warmup')
parser.add_argument('--warmup_steps', default=0, type=int, help='explicit warmup steps; overrides warmup_ratio when > 0')
parser.add_argument('--min_lr', default=1e-6, type=float, help='minimum learning rate after cosine decay')

# ========================= Decoding Settings ==========================
parser.add_argument('--beam_size', type=int, default=3)
parser.add_argument('--do_sample', type=bool, default=False)
parser.add_argument('--no_repeat_ngram_size', type=int, default=2)
parser.add_argument('--num_beam_groups', type=int, default=1)
parser.add_argument('--min_new_tokens', type=int, default=80)
parser.add_argument('--max_new_tokens', type=int, default=120)
parser.add_argument('--max_length', type=int, default=100)
parser.add_argument('--repetition_penalty', type=float, default=2.0)
parser.add_argument('--length_penalty', type=float, default=2.0)
parser.add_argument('--diversity_penalty', type=float, default=0)
parser.add_argument('--temperature', type=float, default=0)

# ========================= KG Entity Label Module ==========================
parser.add_argument('--use_kg_label_loss', default=True, type=lambda x: (str(x).lower() == 'true'), help='add auxiliary KG entity multi-label loss')
parser.add_argument('--kg_label_cache', type=str, default='dataset/mimic_kg_entity_labels.pt', help='cache from scripts/build_kg_label_cache.py')
parser.add_argument('--kg_num_labels', type=int, default=512, help='number of KG entity labels in the cache')
parser.add_argument('--kg_label_loss_weight', type=float, default=0.1, help='weight for KG entity multi-label BCE loss')
parser.add_argument('--kg_label_threshold', type=float, default=0.5, help='threshold for KG label metrics')

# ========================= KG Token Module ==========================
parser.add_argument('--use_kg_tokens', default=False, type=lambda x: (str(x).lower() == 'true'), help='inject RadGraph KG node tokens into the visual projector context')
parser.add_argument('--kg_token_cache', type=str, default='dataset/mimic_radgraph_kg_tokens.pt', help='cache from scripts/build_radgraph_kg_token_cache.py')
parser.add_argument('--kg_max_nodes', type=int, default=64, help='maximum KG nodes per sample')
parser.add_argument('--kg_max_text_tokens', type=int, default=8, help='maximum tokenizer tokens per KG node')
parser.add_argument('--kg_type_vocab_size', type=int, default=8, help='KG entity type embedding vocabulary size')
parser.add_argument('--kg_status_vocab_size', type=int, default=8, help='KG entity status embedding vocabulary size')
parser.add_argument('--kg_relation_vocab_size', type=int, default=16, help='KG relation embedding vocabulary size')
parser.add_argument('--kg_token_dropout', type=float, default=0.1, help='dropout applied to encoded KG node tokens')

# ========================= OPSD Distillation ==========================
parser.add_argument('--teacher_config', type=str, default=None, help='teacher config used by train_opsd.py')
parser.add_argument('--teacher_ckpt_file', type=str, default=None, help='full teacher checkpoint used by train_opsd.py')
parser.add_argument('--teacher_delta_file', type=str, default=None, help='trainable-only teacher checkpoint used by train_opsd.py')
parser.add_argument('--student_ckpt_file', type=str, default=None, help='optional full student checkpoint used by train_opsd.py')
parser.add_argument('--student_delta_file', type=str, default=None, help='optional trainable-only student checkpoint used by train_opsd.py')
parser.add_argument('--opsd_kl_weight', type=float, default=0.5, help='token-level KL loss weight')
parser.add_argument('--opsd_entity_weight', type=float, default=0.1, help='teacher-student KG entity BCE loss weight')
parser.add_argument('--opsd_temperature', type=float, default=2.0, help='distillation temperature for token KL')
parser.add_argument('--opsd_max_kl_tokens', type=int, default=0, help='optional cap on report tokens used for KL per batch; 0 uses all')

# ====================== Pytorch Lightning ===========================
parser.add_argument('--devices', type=int, default=2, help='how many gpus to use')
parser.add_argument('--num_nodes', type=int, default=1, help='Number of GPU nodes for distributed training.')
parser.add_argument('--accelerator', type=str, default="gpu", choices=["cpu", "gpu", "tpu", "ipu", "hpu", "mps"], help='accelerator types')
parser.add_argument('--strategy', type=str, default="ddp", help='default ddp for multi-gpus')
parser.add_argument('--find_unused_parameters', default=False, type=lambda x: (str(x).lower() == 'true'), help='whether DDP should search for unused parameters')
parser.add_argument('--precision', type=str, default='bf16-mixed', help='16 or 32 bf16-mixed, using for original pytorch amp auto cast')
parser.add_argument('--limit_val_batches', type=float, default=1.0, help='How much of validation dataset to check (float = fraction, int = num_batches).')
parser.add_argument('--limit_test_batches', type=float, default=1.0, help='How much of test dataset to check (float = fraction, int = num_batches).')
parser.add_argument('--limit_train_batches', type=float, default=1.0, help='How much of training dataset to check (float = fraction, int = num_batches)')
parser.add_argument('--max_epochs', type=int, default=3, help='Stop training once this number of epochs is reached')
parser.add_argument('--every_n_train_steps', type=int, default=0, help='How many training steps to save a checkpoint')
parser.add_argument('--save_top_k', type=int, default=1, help='number of top validation checkpoints to keep')
parser.add_argument('--early_stop', default=False, type=lambda x: (str(x).lower() == 'true'), help='enable early stopping on validation score')
parser.add_argument('--early_stop_patience', type=int, default=3, help='early stopping patience measured in validation checks')
parser.add_argument('--early_stop_min_delta', type=float, default=0.0, help='minimum val_score improvement for early stopping')
parser.add_argument('--val_check_interval', type=float, default=1.0, help='How often to check the validation set')
parser.add_argument('--metric_val_batches', type=float, default=None, help='temporary validation batch limit used during fit; restores full validation for validate/test commands')
parser.add_argument('--accumulate_grad_batches', type=int, default=1, help='Accumulates gradients over k batches before stepping the optimizer')
parser.add_argument("--num_sanity_val_steps", type=int, default=0, help='Sanity check runs n validation batches before starting the training routine')

# ====================== Branch Predictor ===========================
parser.add_argument('--branch_vocab_path', type=str, default='/public/home/ai_user_5/wxm/MoEPP-Branch/training/vocab.json', help='path to Branch vocab path')
parser.add_argument('--branch_model_path', type=str, default='/public/home/ai_user_5/wxm/MoEPP-Branch/training/branch_model_finetune.pth', help='path to branch model')
